DEFAULT_FOLDER = crkbd/rev1

SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
MUSIC_ENABLE = no
AUDIO_ENABLE = no
COMMAND_ENABLE = no
RGBLIGHT_ENABLE = no
AUTO_SHIFT_ENABLE = no
CONSOLE_ENABLE = no


MOUSEKEY_ENABLE = no
LTO_ENABLE = yes
AVR_USE_MINIMAL_PRINTF = yes
EXTRAKEY_ENABLE = yes
KEY_LOCK_ENABLE = yes
TRI_LAYER_ENABLE = yes
RGB_MATRIX_ENABLE = yes
OS_DETECTION_ENABLE = yes
COMBO_ENABLE = yes
