DEFAULT_FOLDER = crkbd/rev1
KEY_LOCK_ENABLE = yes
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
MUSIC_ENABLE = no
COMMAND_ENABLE = no

RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = no

AUTO_SHIFT_ENABLE = yes
